version: '3.8'

services:
  backend:
    build: ./backend
    container_name: my-node-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: mydatabase
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend-builder
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:latest
    container_name: my-nginx-server
    depends_on:
      - frontend
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    restart: always

  db:
    image: mysql:latest
    container_name: my-mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: