services:
  backend-service:
    image: node:18
    container_name: worktime-backend
    working_dir: /app
    volumes:
      - ../src/backend:/app
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm start"
    depends_on:
      - database-service
    networks:
      - worktime-network

  frontend-service:
    image: node:18
    container_name: worktime-frontend
    working_dir: /app
    volumes:
      - ../src/frontend:/app  # Ensure the correct path
    ports:
      - "3001:3001"
    command: >
      sh -c "ls -la /app && cat /app/package.json && npm install && npm run build"
    depends_on:
      - backend-service
    networks:
      - worktime-network


  reverse-proxy:
    image: nginx:latest
    container_name: worktime-nginx
    depends_on:
      - frontend-service
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../src/frontend/build:/usr/share/nginx/html:ro
    networks:
      - worktime-network

  database-service:
    image: mysql:latest
    container_name: worktime-database
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: worktime_db
      MYSQL_USER: worktime_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - worktime-db-data:/var/lib/mysql
    networks:
      - worktime-network

networks:
  worktime-network:


volumes:
  worktime-db-data:
